# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rXAoZfO0AiUC2wS2SDLO54sB7sU1smSk

modelling
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import mlflow
import mlflow.sklearn

# Load data
df = pd.read_csv("namadataset_preprocessing/cleaned_df.csv")
X = df.drop("berlangganan_deposito", axis=1)
y = df["berlangganan_deposito"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

mlflow.set_experiment("Eksperimen_SML_Royan_Basic")

with mlflow.start_run():
    mlflow.autolog()

    model = RandomForestClassifier(random_state=42)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    print("Accuracy:", acc)